### ISSUE TITLE
couldn't figure out hugo shortcode tweet embed 

### ISSUE THREAD

**Issue by sckott** [ropensci-org/blog-guidance#121]
for the blog post I'm working on https://github.com/ropensci/roweb2/pull/648 I tried the hugo shortcode like `{{ <tweet somenumber> }}` where the source was an .Rmd file, but i couldn't get it to work. I tried putting it inside of `html_preserve` but that didn't work.

**Comment by maelle** [comment]
You mean it disappeared once knit? Did you start from the Rmd template or another Rmd file?

**Comment by sckott** [comment]
another Rmd file, i looked at the template, but maybe I misssed someting

**Comment by stefaniebutland** [comment]
Maëlle see this commit https://github.com/ropensci/roweb2/pull/648/commits/4fe33fa12f34eb1de2fdeeccddb06e2925850b71

Rmd to md created `{{\< tweet 1070733367522590721 \>}}`

**Comment by maelle** [comment]
I commented in the merged PR, the Rmd used didn't have the right output field.

On that output field: What we use is the md by-product of Rmd to html, because no current Rmd md outputs matched our needs, I can't remember exactly why (apart from broken shortcodes). Of course we could create our own output format installed by a package... one day (blogdown. Rmarkdown format could help). In the meantime, we have to use what's in the template (and the resulting html is gitignored and Hugp ignored).

Curious now, why not copy-paste the template btw Scott? Would you prefer to also have a version with just the YAML header or?

**Comment by sckott** [comment]
i just didn' think about it, you know how you get used to a certain workflow, i usually copy paste my old posts

**Comment by stefaniebutland** [comment]
This discussion has been really helpful, esp since this represents a whole new workflow for me and never posted from Rmd before. Helps me know what to look for in others' posts.

@sckott can we close the issue now? Thanks for opening.

**Comment by sckott** [comment]
yes

**Comment by maelle** [comment]
> i just didn' think about it, you know how you get used to a certain workflow, i usually copy paste my old posts

It makes perfect sense! Thank you.
