### ISSUE TITLE
Doc ordering of EN-ES Spanish

### ISSUE THREAD

**Issue by maelle** [ropensci-org/blog-guidance#193]
The key is to use different dates cf https://github.com/ropensci/roweb3/pull/356

**Comment by maelle** [comment]
Not sure _where_ to document this.

**Comment by yabellini** [comment]
What about the editor guidelines?  Something like this:

5.1.5 Post in more than one language

If a blog post has versions in more than one language, in order to sort how they are listed on our website we must use date and time. Check that the date and time in each of the files has the data to appear in the desired order.

**Comment by maelle** [comment]
Yes! Would you like to make a PR?
