### ISSUE TITLE
Add guidance for YAML description

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#56]
in context of twitter cards. suggested number of characters?
YAML description will *not* be used for adding discussion forum topic

**Comment by maelle** [comment]
When there's a Twitter image the card is "summary with large image", otherwise "summary" and both seem to have the same behaviour reg description https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image (iOS, Android: Not displayed - Web: Truncated to three lines in timeline and expanded Tweet) Yeah that's not a number of characters, no idea how to convert lines to characters. The good news is that one can experiment thanks to the card validator...

What's the phrase for a pitch that's even shorter than an elevator pitch? :-)

**Comment by stefaniebutland** [comment]
dumb-waiter pitch? ;-)

> Truncated to three lines in timeline and expanded Tweet
that's helpful

**Comment by stefaniebutland** [comment]
Duplicate of #79 

key point copied manually to #79 so closing this issue
