### ISSUE TITLE
Create team blog-editors

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#62]
So post authors can tag the team and not have to choose which individual

include
@stefaniebutland
@steffilazerte

**Comment by maelle** [comment]
@stefaniebutland I've created the team and opened a private discussion in the team.

Before closing this can you please replace the relevant occurrences of `@stefaniebutland` with `@ropensci/blog-editors` in the book?

**Comment by maelle** [comment]
Also, note that I gave write access to roweb2 to the team so a blog editor only needs to be added to the team (that Stef is a maintainer of) to a) get notified by the handle above b) gain write access to the roweb2 repo.

Where could this be documented? I'd also like to add the rule that any new blog editor needs to have 2FA enabled, because it can't hurt.

**Comment by maelle** [comment]
I _might_ have added an avatar to that team, and if I did, I'm not sorry. :grin:

**Comment by maelle** [comment]
Last comment, if we moved roweb2 to ropensci-org and created the blog-editors there instead, we could add this blog-guidance repo to the team which would be cool.

**Comment by maelle** [comment]
Did I write last comment? Oops. You could use the "projects" tab of the team to have a Kanban board for blog posts with notes, issues (e.g. software review issues with contact taken), post PRs. (but I suspect it might not be useful here, since I think the current organization might be a spreadsheet)

**Comment by maelle** [comment]
I changed the milestone since it's basically done apart from my "move roweb2 to ropensci-org?" question.

**Comment by stefaniebutland** [comment]
> You could use the "projects" tab of the team to have a Kanban board for blog posts with notes, issues (e.g. software review issues with contact taken), post PRs. 

This would be a good thing to seriously consider for lots of reasons.
Note to self: put this somewhere

**Comment by stefaniebutland** [comment]
> Where could this be documented? I'd also like to add the rule that any new blog editor needs to have 2FA enabled, because it can't hurt.

whereiseverything?

**Comment by stefaniebutland** [comment]
Now in [governance chapter ](https://blogguide.ropensci.org/editormeta.html)
