### ISSUE TITLE
better explanation of Twitter cards?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/blog-guidance#79]
Twitter cards still baffle me a bit (have not spent enough time figuring them out). Might not be clear to blog post authors. 

We might need to add some general info to one of Editor "Check Twitter metadata" section or `authortechnical.Rmd` and explain what the effects the important YAML tags have.

**Comment by stefaniebutland** [comment]
See also Add guidance for YAML description https://github.com/ropensci-org/blog-guidance/issues/56

**Comment by stefaniebutland** [comment]
Maëlle, when I see a duplicate issue, how do I close one and include it's content in the other?

**Comment by maelle** [comment]
> Maëlle, when I see a duplicate issue, how do I close one and include it's content in the other? 

I don't know how to include its content in the other issue other than manually. See https://help.github.com/en/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests#marking-duplicates

> Twitter cards still baffle me a bit (have not spent enough time figuring them out). Might not be clear to blog post authors.

Adding some info here in case it helps.

0) A Twitter card means than when pasting the URL in a tweet, what other Twitter users see is not the URL but instead a "card", i.e. the metadata from URL rendered in a nice preview. See e.g. https://twitter.com/nistara_r/status/1225931157159608320 The card makes it more likely someone will want to click on the link because it's prettier and more informative than an URL.

1) where does the info about the post come from

Using YAML metadata and our [theme head partial template](https://github.com/ropensci/roweb2/blob/a19c5e8f371769dcc5d8765577e0d181b254f1bb/themes/ropensci/layouts/partials/head.html#L26-L67) Hugo includes metadata in the page head. see [this post metadata](https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2019-07-16-grainchanger.md) and page head view-source:https://ropensci.org/blog/2019/07/16/grainchanger/ -- no `description:` in the metadata so the first sentences from the post are used.

```
   <meta property="og:title" content="Aggregating spatial data with the grainchanger package - rOpenSci - open tools for open science">
    <meta property="description" content="The grainchanger package provides functionality for data aggregation to a coarser resolution via moving-window or direct methods.
Why do we need new methods for data aggregation? As landscape ecologists and macroecologists, we often need to aggregate data in order to harmonise datasets. In doing so, we often lose a lot of information about the spatial structure and environmental heterogeneity of data measured at finer resolution.
The issues around scale disconnects are both conceptual and practical:">
    <meta property="og:description" content="The grainchanger package provides functionality for data aggregation to a coarser resolution via moving-window or direct methods.
Why do we need new methods for data aggregation? As landscape ecologists and macroecologists, we often need to aggregate data in order to harmonise datasets. In doing so, we often lose a lot of information about the spatial structure and environmental heterogeneity of data measured at finer resolution.
The issues around scale disconnects are both conceptual and practical:">
  <meta property="og:type" content="article">

  
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="https://ropensci.org/img/blog-images/2019-07-16-grainchanger/logo.png" >
  



<meta name="twitter:creator" content="@rOpenSci">
<meta name="twitter:site" content="@rOpenSci">
```

2) how is it used

Twitter consumes the tags that have "twitter:" in their name but also the ones with "og:", see [their reference](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup). Pasting a link into https://cards-dev.twitter.com/validator one sees a preview and a log.

The meta tags are also used by e.g. Slack, Facebook (no idea how the cards look there, I don't use Facebook that has a card validator I think, but with login like the Twitter one so I can't use it). All these places where pasting an URL gets you a rather pretty preview/card of it.

**Comment by stefaniebutland** [comment]
copying key info here from #56 (closed now)

Need more guidance for YAML description in context of twitter cards. 
- suggested number of characters?
- YAML description will not be used for adding discussion forum topic 

from Maëlle:

> When there's a Twitter image the card is "summary with large image", otherwise "summary" and both seem to have the same behaviour reg description developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image (iOS, Android: Not displayed - Web: Truncated to three lines in timeline and expanded Tweet) Yeah that's not a number of characters, no idea how to convert lines to characters. The good news is that one can experiment thanks to the card validator...

**Comment by stefaniebutland** [comment]
addressing in PR #100 and needs @maelle 's input/edits
